export const GROQ_API_KEY = process.env.GROQ_API_KEY || "";
export const CEREBRAS_API_KEY = process.env.CEREBRAS_API_KEY || "";
export const IMAGE_API_BASE = "https://ai-img.webild.workers.dev/img";
export const HN_API = "https://hacker-news.firebaseio.com/v0";
export const DEVTO_API = "https://dev.to/api/articles";

export const WEB_DEV_KEYWORDS = [
  "react",
  "vue",
  "angular",
  "svelte",
  "nextjs",
  "typescript",
  "javascript",
  "css",
  "tailwind",
  "web development",
  "frontend",
  "backend",
  "fullstack",
  "ui",
  "ux",
  "design system",
  "component",
  "framework",
  "performance",
  "webpack",
  "vite",
  "bun",
  "node",
  "deno",
  "api",
  "graphql",
  "rest",
  "webassembly",
  "pwa",
  "responsive",
  "accessibility",
  "a11y",
  "remix",
  "solidjs",
  "qwik",
  "astro",
  "nuxt",
  "gatsby",
  "nuxtjs",
  "angularjs",
  "emberjs",
  "backbonejs",
  "jquery",
  "lodash",
  "rxjs",
  "zustand",
  "mobx",
  "pinia",
  "storybook",
  "mui",
  "chakraui",
  "antd",
  "bootstrap",
  "bulma",
  "shadcn",
  "headlessui",
  "radixui",
  "framer motion",
  "threejs",
  "d3js",
  "esbuild",
  "parcel",
  "rollup",
  "turbopack",
  "rspack",
  "swc",
  "tsup",
  "tsx",
  "pnpm",
  "yarn",
  "npm",
  "docker",
  "podman",
  "kubernetes",
  "k8s",
  "terraform",
  "helm",
  "cicd",
  "github actions",
  "vercel",
  "netlify",
  "cloudflare pages",
  "render",
  "flyio",
  "railway",
  "expressjs",
  "nestjs",
  "fastify",
  "hono",
  "trpc",
  "prisma",
  "drizzle",
  "sequelize",
  "typeorm",
  "mysql",
  "postgresql",
  "mongodb",
  "redis",
  "postgres",
  "supabase",
  "planetscale",
  "convex",
  "edge functions",
  "serverless",
  "lambda",
  "firebase",
  "auth0",
  "clerk",
  "nextauth",
  "stripe",
  "razorpay",
  "lemonsqueezy",
  "firestore",
  "dynamodb",
  "cassandra",
  "cockroachdb",
  "timescaledb",
  "argon2",
  "bcrypt",
  "jwt",
  "oauth",
  "saml",
  "session management",
  "styledcomponents",
  "emotion",
  "styledjsx",
  "vanilla extract",
  "linaria",
  "cssmodules",
  "sass",
  "less",
  "postcss",
  "autoprefixer",
  "grid",
  "flexbox",
  "animations",
  "transitions",
  "darkmode",
  "theming",
  "cssinjs",
  "uno css",
  "lighthouse",
  "core web vitals",
  "lcp",
  "fid",
  "cls",
  "code splitting",
  "lazy loading",
  "tree shaking",
  "bundle analysis",
  "service workers",
  "webp",
  "avif",
  "image optimization",
  "critical css",
  "hydration",
  "vitest",
  "jest",
  "cypress",
  "playwright",
  "testing library",
  "react testing library",
  "msw",
  "e2e",
  "unit testing",
  "integration testing",
  "a11y testing",
  "ai sdk",
  "vercel ai",
  "github models",
  "groq",
  "openai",
  "langchain",
  "webgpu",
  "wasm",
  "rust wasm",
  "go wasm",
  "tauri",
  "electron",
  "capacitor",
  "ionic",
  "flutter web",
  "blazor",
  "server components",
  "rsc",
  "streaming ssr",
  "agentic ai",
  "aws",
  "azure",
  "gcp",
  "cloudfront",
  "route53",
  "cloudinary",
  "imgix",
  "posthog",
  "amplitude",
  "sentry",
  "logrocket",
  "front end developer",
  "website development",
  "web dev",
  "ui developer",
  "web programming",
  "web application development",
  "freelance web developer",
  "python web development",
  "web design and development",
  "web development services",
  "front end web developer",
  "web development company",
  "website developers",
  "ecommerce website development",
  "ui ux developer",
  "web developer jobs",
  "entry level web developer jobs",
  "web development jobs",
  "remote web developer jobs",
  "web development company",
  "web app development company",
  "custom web development",
  "php web development company",
  "wordpress web development company",
  "web development services",
  "custom web development services",
  "ecommerce web development services",
  "web development courses",
  "full stack web development course",
  "free web development courses",
  "web developer course",
  "tsx",
  "mdx",
  "mdsx",
  "contentlayer",
  "remark",
  "rehype",
  "tailwindcss",
  "daisyui",
  "flowbite",
  "heroicons",
  "lucide react",
  "accordion",
  "modal",
  "dropdown",
  "tooltip",
  "carouse",
  "nextui",
  "mantine",
  "radix primitives",
  "aria labels",
  "semantic html",
  "microfrontends",
  "module federation",
  "tanstack query",
  "swr",
  "jotai",
  "valibot",
  "zod",
  "trpc",
  "convex dev",
  "liveblocks",
  "upstash",
  "neon",
  "turso",
  "surrealdb",
  "edgedb",
  "tailwind merge",
  "clsx",
  "class variance authority",
  "cva",
  "pantone",
  "figma dev mode",
  "plasmic",
  "builderio",
  "v0 dev",
  "lovable",
  "cursor ai",
  "github copilot",
  "amazon q",
  "replit agent",
  "cursor composer",
];
